/**
 * las Macrotareas son las cuales que tienen el setTimeout...
 * las macrotaeas y microtareas se relacionan con el event loop,debido a que se van ejecutando en los requerimientos y call stack...
 * se ejecuta la microtarea luego de que la macro tarea se termina cumpliendo...
 * las promesas tienen prioridad frente a los setTimeout en el even loop... 
 */